[project]
name = "python-clear-architecture-and-ddd-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.2",
    "pyright>=1.1.407",
    "ruff>=0.14.9",
]
